### ISSUE TITLE
virtual Linux dev-machine mittels vagrant

### ISSUE THREAD

**Issue by ThorstenCognovo** [miwo100/tikki#1]
Da noch keine finale Entscheidung bzgl. OS, beide Varianten testen:
* Ubuntu &
* Debian

Komponenten die vom provisioner hinzgefügt werden sollen:
* MySQL
* Visual Code
* Meteor (node.js inkl)
* Typings
* (Git/Tortoise-Git)

**Comment by sbmueller** [comment]
Hallo @ThorstenCognovo , ich bin wieder da :)

Da ich übers Wochenende weg bin, mal ein Zwischenstand hierzu:
Für das OS würde ich Ubuntu 16.04 anpeilen. Es ist jedoch noch offen ob wir alle Software in der benötigten Version dort in den Repos bekommen. Für Debian & Fedora gibt es keine aktuellen Base-Boxen.
Ich schreibe gerade am Vagrantfile und am Provisioning-Skript. Die Maschine startet schon, jedoch ist aktuell das Problem, dass Vagrant beim Einbinden der geteilten Ordner hängen bleibt. Der Grund ist der Fehlermeldung nach wahrscheinlich dieser hier: https://nickescobedo.com/719/ubuntu-apt-get-hangs-at-0. Es gibt anscheinend Probleme mit IPv6 und man muss Ubuntu zwingen, IPv4 zu nutzen. Ich versuche deswegen gerade, das provisioning-Skript VOR dem Einbinden der Ordner laufen zu lassen um einen Fix hierzu einzuspielen. 

Auch wichtig: Alle Base-Boxen kommen ohne Window Manager! Gut, denn wir können uns selber einen aussuchen. Aber auch schlecht, denn wir müssen uns um die Installation kümmern. Ich würde hier entweder XFCE (https://www.xfce.org/) oder i3 (https://i3wm.org/) nehmen. i3 ist eher für fortgeschrittene Nutzer gedacht, aber ich habe über den Sommer sehr gut damit gearbeitet. Die Installation würde ich dann demnächst im Provisioning-Skript angehen.

**Comment by ThorstenCognovo** [comment]
Hi Sebastian! Willkommen zurück! Schön, dass du wieder an Bord bist 😃 🎉 
Vielen Dank für deinen ausführlichen Statusbericht. Das hört sich ja schon sehr vielversprechend an 👍 
Ich selbst habe bisher keinerlei Erfahrung mit Ubuntu und auch nur wenig Erfahrung mit vagrant.
Daher kann ich zur Lösung des Problems mit IPv6 <> IPv4 leider nicht allzuviel beitragen. Das von dir vorgeschlagene Vorgehen finde ich aber sehr plausibel!
Super, dass du auch schon Erfahrung mit Window Managern hast. Damit bist du mir auch in diesem Thema voraus und ich würde da erstmal auf deine Erfahrungswerte vertrauen. 
Sprich das aber vielleicht auch noch einmal mit @miwo100 ab, falls er hier bestimmte Präferenzen hat.

**Comment by sbmueller** [comment]
Die Maschine kann ich nun starten, jedoch nur mit etwas manuellem Zutun. Ich muss noch etwas finetuning betreiben, bis alles von alleine läuft.
![image](https://cloud.githubusercontent.com/assets/7465688/19556036/9acf39be-96bf-11e6-80cc-d3338566a0ba.png)
Das IPv6 Problem konnte ich beheben, indem ich IPv6 in meinem privaten Router deaktiviert habe. Wenn ihr wollt, könnt ihr den `vagrant` Branch mal ausprobieren und melden, was passiert.

Wenn eine Meldung kommt "could not lock administration dir", dann einfach nochmal `vagrant up` versuchen (dann ist die VM noch nicht fertig gebootet).

**Comment by miwo100** [comment]
Hi @sbmueller , wie kann ich denn testen ?

**Comment by miwo100** [comment]
ok, hab die Version auf dem vagrant branch entdeckt und teste jetzt

**Comment by miwo100** [comment]
das ist das Ergebnis, leider noch nicht erfolgreich:

![image](https://cloud.githubusercontent.com/assets/5810399/19646585/608ce5f6-99fa-11e6-9fce-e6fe414e218b.png)

**Comment by miwo100** [comment]
wenn ich mich mit der HyperV Maschine verbinde, sehe ich das hier:

![image](https://cloud.githubusercontent.com/assets/5810399/19646624/8e609112-99fa-11e6-939e-5f746bfecbe3.png)

**Comment by sbmueller** [comment]
Das ist alles schonmal ok so. Du solltest dich jetzt mit User und Passwd `vagrant` einloggen können und mit `sudo startxfce4` den Window Manager starten können. Ich muss noch überlegen, wie man das automatisieren kann.

**Comment by miwo100** [comment]
![image](https://cloud.githubusercontent.com/assets/5810399/19648121/5f11d130-9a01-11e6-8ecf-6a5ce38463a1.png)

Kannst Du mir das noch durchgeben ?

**Comment by miwo100** [comment]
und dann auf einmal, nachdem ich nichts eingegeben habe:

![image](https://cloud.githubusercontent.com/assets/5810399/19648206/a790e824-9a01-11e6-820c-5737c12d7781.png)

**Comment by sbmueller** [comment]
Du musst dich zuerst als user `vagrant` anmelden.

**Comment by miwo100** [comment]
und das Passwort ?

![image](https://cloud.githubusercontent.com/assets/5810399/19648414/585284ce-9a02-11e6-8fa6-0bc1f02f06cb.png)

**Comment by miwo100** [comment]
![image](https://cloud.githubusercontent.com/assets/5810399/19648561/b45e5fb8-9a02-11e6-8b7a-eebfc53e3998.png)

**Comment by miwo100** [comment]
YIPEEE

**Comment by miwo100** [comment]
Super, das Tikki Projektverzeichnis ist auch da. Bitte hierfür auch noch einen Link auf dem Desktop vorsehen.

**Comment by miwo100** [comment]
hier fehlt jetzt nur noch das automatische Starten des xfce4 Window Managers

**Comment by sbmueller** [comment]
Der Issue ist denke ich nun abgeschlossen. Leider ist es bei Hyper-V nicht möglich, die GUI von Vagrant aus aufzurufen. Somit muss nach dem `vagrant up` die Maschine noch in Hyper-V geöffnet werden.
Danach mit cognovo/congovo anmelden und die Maschine sollte bereit sein.

**Comment by miwo100** [comment]
Wir die GUI dann nach der Anmeldung automatisch gestartet?

**Comment by sbmueller** [comment]
Ja, GUI sollte automatisch starten nach der Anmeldung.
Wie sieht es bei dir mit der Performance aus? Ich bin gerade an #5 und bei mir ist alles sehr träge und verzögert.

**Comment by miwo100** [comment]
Die Verbindung auf den smb folder dauert bei mir lange, aber nur beim ersten Vagrant up. Der provisioner läuft ja nur beim ersten Vagrant up, insofern ist das nicht so tragisch.

Von meinem iPhone gesendet

**Comment by sbmueller** [comment]
Ich meine die virtuelle Maschine an sich, nicht den provisioner
