### ISSUE TITLE
build development pipeline on base of heroku

### ISSUE THREAD

**Issue by miwo100** [miwo100/tikki#2]
please build a development pipeline like this one:

![image](https://cloud.githubusercontent.com/assets/5810399/21896648/6b3506ba-d8e7-11e6-846e-7a1ff41cadf3.png)

**Comment by miwo100** [comment]
The integration grom github to travis already exists. So pls focus on the integration between travis and heroku.

**Comment by miwo100** [comment]
On heroku, pls provide the following:

- MySql database server with one database. The name of the database must be __tikki__. Tables do not need to be created.

- graphqlServer: node express application that need to be startet as described here: https://github.com/miwo100/tikki The graphqlServer is provided for data access requests from the webApp. It reaches out to mysql and the github api.

- webApp: web application, node express application. To start follow this: https://github.com/miwo100/tikki

- Last but not least one URL which will direct the tester to tikki webApp.

**Comment by miwo100** [comment]
Accounts:
github: miwo100
travis: über github anmelden
heroku: michael-wolff@t-online.de

passwords follow as usual.

**Comment by sbmueller** [comment]
I have changed the `.travis.yml` file as well as created an app on heroku. Deployment of the code now works, but the app fails to start. Have to take a 2nd look, but AFAIK the app can not run without a token provided in `graphqlServer/config/local.json`

**Comment by sbmueller** [comment]
Ich habe immernoch Probleme, die App auf Heroku zu starten. Der aktuelle Fehler ist `ng: not found` wobei ng von der webApp aufgerufen wird. Ausserdem musste ich eine package.jsom im root-folder anlegen, damit Heroku die zwei Apps als eine erkennt. Da ich mich null mit Node auskenne, probiere ich da einfach blind rum.
Ich habe noch das hier gefunden, wo empfohlen wird, keine `node_modules` Ordner in die Repo aufzunehmen:
https://devcenter.heroku.com/articles/troubleshooting-node-deploys#don-t-check-in-generated-directories

**Comment by sbmueller** [comment]
@miwo100 making no progress here. Can't figure out what's wrong, but seems like a node issue. Still getting `ng: not found` while angular gets installed during build process.

**Comment by miwo100** [comment]
ng seems to be angular-cli, try first to globally install angular-cli something like npm install angular-cli --global -- save

**Comment by miwo100** [comment]
Or look for angular-cli and see how to install it...

**Comment by sbmueller** [comment]
I don't think this causes the issue, because
1. I did't have to take any extra steps when running tikki locally
2. I can see from the logs that angular gets installed during build

**Comment by miwo100** [comment]
We are not using meteor anymore. We develop in the angular-cli environment. You cannot get it running without angular-cli

**Comment by sbmueller** [comment]
See https://github.com/miwo100/tikki/blob/pipeline/heroku.log for current error messages on heroku.

**Comment by ThorstenCognovo** [comment]
**Update:** This architecture won't be realised anymore but will be replaced by an architecture based on *docker*
