### ISSUE TITLE
Projektcode erstellen

### ISSUE THREAD

**Issue by ThorstenCognovo** [miwo100/tikki#4]
Wo ich hier gerade die Standard-Labels & Milestones erstellt habe, dachte ich: vielleicht wäre auch ein separater Projectcode hierfür sinnvoll? Dann läuft nicht alles auf INTINFRA...

Was denkst du, @miwo100?

**Comment by miwo100** [comment]
ja ein tikki projekt Code wäre sinnvoll. Sehr gute Idee.
