### ISSUE TITLE
ubuntu provisioning

### ISSUE THREAD

**Issue by miwo100** [miwo100/tikki#5]
Bitte vorerst Folgendes auf Ubuntu bereitstellen (wird weiter ergänzt)

**Das Wichtigste vorweg: bitte alle Installationen unter dem user vagrant durchführen, __NICHT als root user**. Im Terminal musste ich dazu immer su - vagrant verwenden. Wie das über SSH funktioniert weiß ich nicht, vermutlich genauso ?
- [x] Meteor https://www.meteor.com/install
- [x] Node über NVM installieren (siehe unten)
- [x] Chrome mit Link auf Desktop und Taskleiste (falls es sowas gibt)
- [x] Visual Code mit Link auf Desktop und Taskleiste (falls es sowas gibt)
- [x] mysql-server and mysql-client mit password cognovo für root user 
  http://www.cyberciti.biz/faq/howto-install-mysql-on-ubuntu-linux-16-04/
- [x] mysql-workbench

```
sudo apt-get install mysql-workbench
```
- [x] Sublime mit Link auf Desktop und Taskleiste (falls es sowas gibt)
- [ ] Copy Paste Support vom windows host zum ubuntu guest
- [x] Terminal Fenster konfigurieren (siehe unten)

**Comment by miwo100** [comment]
bitte noch ein schönes Terminalfenster (background black, forgroud white) und lesbar :-)

**Comment by miwo100** [comment]
ich musste noch folgendes machen, damit npm install funktioniert:

https://docs.npmjs.com/getting-started/fixing-npm-permissions
__WICHTIG__: bitte Option 2

**Comment by miwo100** [comment]
neuen user cognovo anlegen:
adduser cognovo -> new user cognovo (without interaction required) password cognovo
usermod -aG sudo cognovo  -> add to group sudo to get all permissions
installation of all software done with cognovo user

**Comment by miwo100** [comment]
npm install funktioniert nur, wenn zusätzlich für ~/.config Eigentümerschaft auf cognovo übergeben wird:
```
sudo chown -R $USER:$GROUP ~/.config
```
dies im context von cognovo user ausführen

**Comment by miwo100** [comment]
npm install funktioniert nur, wenn zusätzlich für ~/.config Eigentümerschaft auf cognovo übergeben wird:
```
sudo chown -R $USER:$GROUP ~/.config
```
dies im context von cognovo user ausführen

**Comment by sbmueller** [comment]
Ich habe den provisioner nun in der "Beta" fertig. Die abgehakten Punkte sollten funktionieren, sonst habe ich noch folgende Anmerkungen:
- Die Desktopicons sind schwer durch die Konsole zu erstellen, jedoch mit 2 Klicks schnell in der GUI erstellt. Der Aufwand, das im provisioning zu erledigen, ist deswegen viel größer. Kann ich aber machen, falls gewünscht.
- Statt Chrome wird Chromium installiert. Ist das selbe, heißt nur anders.
- Ich konnte erstmal nicht verifizieren, dass ein shared clipboard von Vagrant mit Hyper-V unterstützt wird. In der Doku steht dazu nichts, somit denke ich, dass das nicht möglich sein wird. 
- Ich hatte noch nicht genug Zeit, das ganze ausführlich zu testen (jedes frische provisioning dauert ca. 30 min, meine Zeiterfassung freut sich dafür)

Du kannst den Stand gerne mal ausprobieren und melden, wenn etwas noch nicht funktioniert.

**Comment by miwo100** [comment]
Alles klar, danke erstmal!

Von meinem iPhone gesendet

**Comment by miwo100** [comment]
leider bekomme ich bei vagrant up nur noch folgendes, vor Deinen letzten Änderungen hat es funktioniert:
![image](https://cloud.githubusercontent.com/assets/5810399/19869129/49555114-9fab-11e6-8474-b40228def247.png)

**Comment by sbmueller** [comment]
Achso klar. Problem ist, dass ich nicht jedes mal eine neue Maschine provisioniere (was sonst noch laenger dauern wuerde).
Das provisioner-script wird erst am Ende des `vagrant up` aufgerufen. Dort wird dann auch erst der neue Benutzer cognovo erstellt. Jedoch wird schon vorher versucht, den shared folder Tikki unter dem User cognovo zu mounten, den es da ja noch gar nicht gibt. Ich versuche einen anderen Ansatz.

**Comment by sbmueller** [comment]
Der Fehler sollte jetzt behoben sein, aber einige Sachen funktionieren noch nicht, wie sie sollen:
- Trotz der Anleitung zu NVM funktioniert die Installation von node.js damit nicht (command nvm not found)
- XFCE4 ist buggy und muss manuell noch gefixt werden (einmal ein- und ausloggen, dann wieder einloggen und `xfce4-panel` aufrufen). Keine Ahnung woran das liegt.
- Meteor wird als root installiert, da das Installationsscript Zugriff auf Systemverzeichnisse benoetigt. Ich weiss nicht, ob das ein Problem ist.

Kannst du nochmal testen?

**Comment by sbmueller** [comment]
Nach langem Herumprobieren komme ich einer Lösung näher:
- XFCE wird nun anders installiert und scheint nun keine Probleme mehr zu machen. Auch das Anmelden funktioniert nun grafisch.
- Node konnte ich nicht mit NVM installieren, es wird nun per Paketmanager installiert. Kannst du mir nochmal Rückmeldung geben, was dann genau das Problem ist? Vielleicht ist es einfacher, diese Lösung anzupeilen.

Im Moment sollte alles so funktionieren:
1. `vagrant up` installiert die Maschine, wirft dann aber einen Fehler beim Einbinden des geteilten Ordners. Das liegt daran, dass ich das provisioner-Skript nicht vor den Vagrant eigenen Skripten starten kann.
2. Nochmal `vagrant up` überspringt warum auch immer den geteilten Ordner und führt das Provisioning aus.
3. Maschine herunterfahren und ein drittes mal mit `vagrant up` starten sollte nun auch den Tikki Ordner auf dem Desktop bereitstellen.

@miwo100 Kannst du mir bitte Rückmeldung dazu geben?

**Comment by miwo100** [comment]
Ich war die ganze Woche unterwegs und jetzt im Schwarzwald. Morgen Abend werde ich mal testen. Mist dass dass das so kompliziert ist 😫

Von meinem iPhone gesendet

**Comment by sbmueller** [comment]
Alles klar, unabhängig von diesem Issue sollten wir aber auch in Betracht ziehen, Linux eventuell parallel zu Windows zu installieren. Wie schon bei #1 angedeutet, ist die VM bei mir so träge, dass arbeiten darauf praktisch nicht möglich ist. Bei dir könnte das wegen stärkerer Hardware aber anders aussehen.

**Comment by miwo100** [comment]
Ich bin wieder unterwegs, werde mir das diese Woche ansehen. Wichtig ist, dass alles ohne Unterbrechung hochfährt.

Von meinem iPhone gesendet

**Comment by miwo100** [comment]
Ich habe mit dieser Maschine getestet:
```
  #config.vm.box = "kmm/ubuntu-xenial64" # this is the only Ubuntu 16.04 box available
  config.vm.box = "ericmann/trusty64" #14.0.4
```
Damit funktioniert das Einbinden des SMB Folders auf Anhieb :-)

Falls nötig kann man später noch ein Skript laufen lassen um von 14.04 auf 16.04 anzuheben. Das vorneweg, bin noch am testen.

**Comment by miwo100** [comment]
bei der Ausführung von chown -R cognovo:cognovo /home/cognovo/.npm:

==> default: chown:
__==> default: cannot access ‘/home/cognovo/.npm’__
==> default: : No such file or directory
==> default: Error installing node.js

bitte nochmals prüfen

**Comment by sbmueller** [comment]
Oh, diese Linie war noch ein Fragment aus der NVM Installation, die nicht funktionierte. Trotz der Meldung sollte nodejs installiert sein.

**Comment by sbmueller** [comment]
Hast du deine Änderungen gepushed?

**Comment by miwo100** [comment]
Nein leider nicht, aber das einzige was ich geändert habe ist die base Box, teste bitte mal mit der. Da funktioniert das erstellen des Samba shares perfekt.

Von meinem iPhone gesendet

**Comment by sbmueller** [comment]
>Nein leider nicht, aber das einzige was ich geändert habe ist die base Box, teste bitte mal mit der. Da funktioniert das erstellen des Samba shares perfekt.

Die `ericmann/trusty64` funktioniert bei mir auch ganz gut. Jedoch hängt vagrant bei mir beim Installieren des xfce4 (30 min ohne Fortschritt). Ich musste dann das provisioning abbrechen und nochmal neu anstoßen, danach ging es.
Außerdem musste ich die Maschine einmal neu starten, damit die GUI automatisch hochfährt.

>bei der Ausführung von chown -R cognovo:cognovo /home/cognovo/.npm:
>
>==> default: chown:
>==> default: cannot access ‘/home/cognovo/.npm’
>==> default: : No such file or directory
>==> default: Error installing node.js
>
>bitte nochmals prüfen

Die Warnung ist nun weg. Ich kann bei mir eine `node`-Konsole starten. Ich denke also, node.js wurde richtig installiert. Der Shared Folder funktioniert auch gut.
Ich warte dann auf deine Rückmeldung, ob noch etwas Probleme macht.

**Comment by miwo100** [comment]
kannst Du bitte auch noch https://github.com/miwo100/novo/issues/28 berücksichtigen.
Bitte die ersten zwei Punkte beachten. Vielen Dank!

@ThorstenCognovo  und ich haben entschieden, das Projektverzeichnis nicht mehr vom Host zum Guest durchzureichen, weil das beim Kompilieren nur Probleme macht. Stattdessen wollen wir auf jedem Notebook ein c:\VMShare wie beschrieben einrichten, über das man dann Dateien zwischen Host und Guest austauschen kann. 

Das Projektverzeichnis dann bitte nicht mehr sharen und stattdessen nur noch c:\VMShare.

**Comment by sbmueller** [comment]
Update aus Chat mit @miwo100 :
1) Zweimaliges Neustarten beim Setup ist zu viel. Es darf max. einmal neu gestartet werden.
2) Das System soll direkt auf 16.04 upgegraded werden.

**Comment by miwo100** [comment]
Und dritte Anforderung:
Nach dem provisioning muss die Maschine nach Vagrant up sofort( ohne Neustart) bereitstehen 

Von meinem iPhone gesendet

**Comment by sbmueller** [comment]
Ich versuche hier mal die Dokumentation upzudaten und mache den Issue zu. Dafür kommt ein neuer Issue bzgl. der custom basebox.

**Comment by sbmueller** [comment]
@miwo100 will nun doch Virtualbox als Alternative zu HyperV mit diesem Ansatz testen. Erste Tests verliefen ganz gut.

**Comment by sbmueller** [comment]
Wie immer muss einmal nach dem provisioning neu gestartet werden, damit die korrekten Kernel-Module geladen werden. Danach bitte mit vagrant/vagrant einloggen. User cognovo ist nur zu Testzwecken noch da.

**Comment by miwo100** [comment]
funktioniert perfekt, ich musste nach dem provisioning zweimal starten.

**Comment by miwo100** [comment]
bitte noch das deutsche Tastaturlayout aktivieren:

```
Setxkbmap de
```

**Comment by miwo100** [comment]
bitte auch noch diese beiden Punkte berücksichtigen:

- [ ] den lokalen Host Folder C:\VMShare per smb als ~/VMShare einbinden 
- [ ] den lokalen Host Folder C:\Backup\Tikki nicht mehr per smb einbinden 

Hintergrund: meteor funktioniert auf einem gesharten Folder nicht richtig, macht nur Probleme :-)
Wir klonen das Projekt Verzeichnis dann von github direkt in den vagrant home folder mittels Visual Code.

**Comment by miwo100** [comment]
dann bitte auch noch git mit aufnehmen:

```
apt-get install git
```

**Comment by miwo100** [comment]
und ich bräuchte noch den root user + password

**Comment by miwo100** [comment]
and the list goes on:
- [ ] npm auf aktuelle Version (müsste 4.0.3 oder höher sein) heben:
```sudo npm install npm@latest -g``` 
- [ ] typings global installieren
```sudo npm install typings -g```

**Comment by sbmueller** [comment]
Sollte nun alles gehen :)

**Comment by sbmueller** [comment]
Um die Maschine frisch aufzusetzen, muss der `.vagrant` Ordner unter tikki und die Box unter `.vagrant.d\boxes` im Home-Verzeichnis geloescht werden.

**Comment by miwo100** [comment]
ok, dann werde ich gleich mal testen

**Comment by miwo100** [comment]
ich hatte Probleme mit dieser Zeile:
```config.vm.synced_folder "C:\VMShare", "/VMShare", owner: "vagrant", group: "vagrant"```
korrekt muss es lauten (Doppelbackslash)
```config.vm.synced_folder "C:\\VMShare", "/VMShare", owner: "vagrant", group: "vagrant"```

Warum hat es dann bei Dir funktioniert ?

**Comment by miwo100** [comment]
![image](https://cloud.githubusercontent.com/assets/5810399/21081853/af262b14-bfcf-11e6-9eb4-a786aafec677.png)

Warum wird eigentlich immer noch c:\backup\tikki geshared ? Kann ich im vagrant file nirgends finden ??

**Comment by sbmueller** [comment]
Kann ich dir gerade auch nicht sagen. Hast du die beiden Ordner gelöscht?

**Comment by miwo100** [comment]
Ja 👍 Mappe er aber trotzdem

Von meinem iPhone gesendet

**Comment by miwo100** [comment]
Einen Fehler habe ich noch entdeckt :-)
Zeile 62 und 63 sollte installiert werden, nachdem node installiert wurde, bitte noch anpassen.
![image](https://cloud.githubusercontent.com/assets/5810399/21082333/f78a7874-bfd9-11e6-849a-64ffd8f50f67.png)

**Comment by miwo100** [comment]
und erst Typings installieren und DANN npm upgraden, also gerade in umgekehrter Reihenfolge.

**Comment by miwo100** [comment]
ich pass das selbst schnell an und teste dann nochmals...

**Comment by miwo100** [comment]
@sbmueller , das deutsche Tastaturlayout fehlt noch, bitte noch ergänzen...

**Comment by sbmueller** [comment]
Deutsches Layout müsste bereits drin sein und hat bei mir funktioniert (letzte Zeilen im provisioner skript). Was istd der Inhalt der dort gelisteten Datei bei dir?

**Comment by miwo100** [comment]
jawoll, beim Restart hat es funktioniert, vielen Dank!!

**Comment by miwo100** [comment]
und bitte diese Zeile noch einbauen: meteor INotify File Change fix:
```echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p```
https://github.com/meteor/docs/blob/version-NEXT/long-form/file-change-watcher-efficiency.md
bitte nach der Installation von meteor einfügen

**Comment by miwo100** [comment]
per ifconfig (statt ipconfig) kann man die Guest ip Adresse rauskriegen und dann vom host aus auf den guest per Chrome gehen.

Schöner wäre natürlich http://localhost:3000

das sollte umgeleitet werden auf den linux guest localhost:3000

@sbmueller, weißt Du was ich meine ?

Kannst Du das umsetzen. Vielleicht über eine Portumleitung vom Host zum Guest ?

Ziel wäre, dass der Guest immer unter der gleichen Adresse für alle erreichbar ist.,

**Comment by sbmueller** [comment]
Da sehe ich zwei Probleme:
1) Netzwerktechnisch handelt es sich bei Host und Guest um zwei Rechner, auch wenn sie auf der selben Hardware laufen. `localhost` ist dabei immer stellvertretend fuer die Maschine, auf der der Befehl aufgerufen wird. `localhost` auf dem Host umzuleiten, halte ich fuer sehr gefaehrlich, da viele Programme auf diese Identitaet bauen. Im schlimmsten Fall zerschiesst man sich da das System. Eventuell gibt es Programme, die nur einzelne Ports umleiten, aber `localhost` sollte fuer jeden Port auf den "lokalen Host" zeigen.
2) Im Moment bekommt der Guest eine IP vom Router im lokalen Netzwerk. Man kann zwar eine feste IP vergeben, jedoch muss diese auf die lokale Umgebung angepasst sein, und zwar fuer jeden Mitarbeiter, der den Guest verwenden moechte. Die feste IP muss dabei ausserhalb des Addressrange des jeweiligen DHCP Servers liegen und muss ausserdem die selbe Subnetzmaske etc. befolgen.

Mir faellt diese einfache Loesung, die diese Probleme umgeht, ein: Der Guest koennte nach dem Start eine index.html in C:\VMShare anlegen, die eine Umleitung auf die aktuelle IP enthaelt. So muss man beim Arbeitsbeginn nur einmal die Datei oeffnen.

**Comment by miwo100** [comment]
Ich geb dir vollkommen recht, ich mich mit localist auch nicht klar genug ausgedrückt. Ich meinte eher http://tikkidev/... und tikkidev soll automatisch auf die Entwicklungsmaschine gehen... Moment mal , hat die Entwicklungsmaschine nicht schon einen Netzwerknamen?

Von meinem iPhone gesendet

**Comment by sbmueller** [comment]
Das mit dem Port war super Einfach. Virtualbox unterstützt Portweiterleitungen auf den Guest, also kein Problem. Die VM ist nun unter `localhost:3000` erreichbar. Bei mir hat die Anwendung noch geladen, aber scheint zu klappen:
![image](https://cloud.githubusercontent.com/assets/7465688/21286876/3338db2e-c460-11e6-80a6-fc16e8219a94.png)

**Comment by miwo100** [comment]
Sehr schön Sebastian!!

Von meinem iPhone gesendet
