### ISSUE TITLE
Cognovo BaseBox erstellen

### ISSUE THREAD

**Issue by sbmueller** [miwo100/tikki#6]
Nachdem sich #5 als problematischer als gedacht herausgestellt hat (alle BaseBoxen sind Minimalsysteme auf die wir einiges an Software packen müssen, was zu den verschiedensten Problemen führt), haben wir uns entschlossen, eine eigene BaseBox für Cognovo zu erstellen. Diese ist nicht so minimalistisch wie die offiziellen, sondern liefert schon die Xfce GUI von Haus aus mit (die damit problemlos funktioniert). Es müssen somit nur noch einige Tools im Provisioning installiert werden.

**Comment by sbmueller** [comment]
Nnach einigem Einlesen gibt es nun noch folgendes Problem: Ab Win10 ist vagrant nichtmehr kompatibel mit den Virtuellen Maschinen aus HyperV, sofern man eine BaseBox aus diesen erstellen möchte (s. https://github.com/mitchellh/vagrant/issues/7706). Ich habe nun 3 Optionen abgeklopft:
1) Matt Wrocks Lösung um VirtualBox-Maschinen nach HyperV umzuziehen (http://www.hurryupandwait.io/blog/creating-a-hyper-v-vagrant-box-from-a-virtualbox-vmdk-or-vdi-image). Er schreibt jedoch selbst, dass das Kernproblem mit Win10 damit erhalten bleibt. Er selbst nutzt Win8 für den Post.
2) Der genannte Vagrant-Issue ist geschlossen, anscheinend ist das Problem gefixed. Jedoch wird der Fix erst in v. 1.9.0 öffentlich. Man könnte vagrant nun selbst aus den Quellen bauen, aber das scheitert schon im ersten Schritt, weil in den Dokumentationen Linux vorausgesetzt wird. Ich denke nicht, dass das auf Windows möglich ist.
3) Win8 installieren und dort die Box bauen. Das bliebe noch übrig, aber ich bräuchte dann nochmal eine Lizenz von dir @miwo100 .

**Comment by sbmueller** [comment]
@miwo100 habe deinen Vorschlag überprüft. Die XML bietet keinen Parameter bezüglich der Plattengröße, sondern verweist einfach nur auf die Festplattendatei. Diese habe ich mit HyperV vergrößert, trotzdem ist in der VM nicht mehr Platz.
Ich bin immernoch dafür, unsere eigene BaseBox zu bauen, da wir damit viele problematische Aktionen im Provisioner (Upgrade auf 16.04, blindes Vergrößern mehrerer Partitionen, ...) umgehen können und dort nur die Tools installieren müssen, was deutlich einfacher von der Hand geht.

**Comment by miwo100** [comment]
Dann zieh dir am besten eine virtuelle win8.1 Box auf hyperv und Bau in dieser umgebung die ubuntu base Box. Macht das Sinn?

Von meinem iPhone gesendet

**Comment by sbmueller** [comment]
Ja, kann ich Win8 downloaden und ohne Lizenz benutzen?

**Comment by miwo100** [comment]
Ja klar, wenn das geht kein Problem vobn meiner Seite...

Von meinem iPhone gesendet

**Comment by sbmueller** [comment]
@miwo100 Klappt bei mir irgendwie nicht. Ich glaube ich brauche eine Lizenz.
![image](https://cloud.githubusercontent.com/assets/7465688/20865249/67a1e9bc-ba0d-11e6-9eaa-2044834dc5aa.png)

**Comment by miwo100** [comment]
@sbmueller bitte vorerst hier nicht weiter machen. Wir verfolgen jetzt erst mal den Ansatz eine VM unter Azure bereitzustellen.

**Comment by ThorstenCognovo** [comment]
Update: Dieser Ansatz wird nun auch verworfen; Wir verwenden eine Standard-VirtualBox-(BaseBox)
