### ISSUE TITLE
Ubuntu Server als Azure VM einrichten

### ISSUE THREAD

**Issue by miwo100** [miwo100/tikki#7]
Eine Azure VM in der Cloud hat den Vorteil, dass wir keine lokalen Hardware Ressource benötigen. @sbmueller hatte bereits festgestellt, dass die Hyper-v Maschine recht träge auf seiner Hardware läuft.

Hier nun der Versuch, die Maschine über das Azure Portal einzurichten.

**Comment by miwo100** [comment]
Maschine in Azure entsprechend dieser Anleitung hochziehen:
https://blogs.technet.microsoft.com/uktechnet/2013/11/12/running-a-remote-desktop-on-a-windows-azure-linux-vm/
Dabei auch folgenden Link beachten:
https://docs.microsoft.com/de-de/azure/virtual-machines/virtual-machines-linux-classic-remote-desktop
Insbesondere Abschnitt "Verwenden Sie Xfce , wenn Sie eine neuere Ubuntu-Version als Ubuntu 12.04LTS verwenden."
Was hier vergessen worden ist, zu erwähnen: Installation von XFCE4:
```sudo apt-get install xfce4```

**Comment by miwo100** [comment]
die Maschine ist soweit eingerichtet, bitte nun alles was Du für vagrant provisioned hast: Chrome etc. hier installieren, merci.

**Comment by miwo100** [comment]
Verbindungsinfos folgen noch!

**Comment by sbmueller** [comment]
@miwo100 ok, werde es mir am Samstag anschauen. Kannst du mir bis dahin die Verbindungsinfos mailen?

**Comment by sbmueller** [comment]
Update: Statt Azure ist definitiv https://c9.io/ oder https://www.digitalocean.com/ eine bessere Alternative, die wir uns anschauen wollen. Ausserdem wird fuer #5 noch Virtualbox als Provider ausprobiert.

**Comment by ThorstenCognovo** [comment]
Update: Da der Test unter #5 mit virtualbox erfolgreich war, wird das hier geschlossen; kein externes Hosting der Entwicklungsumgebung!
